## Model Selection
### K-fold Cross Validation


In [674]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [675]:
# dataset = load_iris()
# data = pd.DataFrame(dataset.data,columns=dataset.feature_names)
# data['target'] = dataset.target
# data = data.sample(frac=1)
# X = np.array(data.drop(['target'],axis=1))
# Y = np.array(data['target'])

In [676]:
dataset = load_digits()
X = dataset.data
Y = dataset.target

In [677]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
X_scaled = StandardScaler().fit_transform(X)
X_standard = PCA(n_components=0.98).fit_transform(X_scaled)
X = X_standard

In [678]:
def getscore(model,X_train,Y_train,X_test,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [679]:
from sklearn.model_selection import StratifiedKFold
score_lr = []
score_svm = []
score_rf = []

kf = StratifiedKFold(n_splits=5,shuffle=True)

for train_index, test_index in kf.split(X,Y):
    score_lr.append(getscore(LogisticRegression(max_iter=10000),X[train_index],Y[train_index],X[test_index],Y[test_index]))
    score_svm.append(getscore(SVC(C=1,kernel='linear'),X[train_index],Y[train_index],X[test_index],Y[test_index]))
    score_rf.append(getscore(RandomForestClassifier(n_estimators=100),X[train_index],Y[train_index],X[test_index],Y[test_index]))

print(score_lr,'\n',score_svm,'\n',score_rf)

[0.9694444444444444, 0.9555555555555556, 0.9832869080779945, 0.9693593314763231, 0.9637883008356546] 
 [0.9833333333333333, 0.975, 0.9860724233983287, 0.9693593314763231, 0.9805013927576601] 
 [0.975, 0.95, 0.9721448467966574, 0.9665738161559888, 0.9610027855153204]


In [680]:
print(np.average(score_lr),
np.average(score_svm),
np.average(score_rf))

0.9682869080779944 0.978853296193129 0.9649442896935932


In [681]:
from sklearn.model_selection import cross_val_score

In [682]:
print(cross_val_score(LogisticRegression(max_iter=10000),X,Y))
print(cross_val_score(SVC(C=1,kernel='linear'),X,Y))
print(cross_val_score(RandomForestClassifier(n_estimators=100),X,Y))

[0.91944444 0.88333333 0.94150418 0.96657382 0.89693593]
[0.94722222 0.925      0.9637883  0.98050139 0.92200557]
[0.92777778 0.89166667 0.95264624 0.94986072 0.90807799]
