# Numpy tutorial

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
a=np.array(a)
a

array([1, 2, 3, 4])

In [3]:
b=[[1,2],[3,4]]
b=np.array(b)
b

array([[1, 2],
       [3, 4]])

### Reshaping of numpy array

In [4]:
a.shape

(4,)

In [5]:
b.shape

(2, 2)

In [6]:
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [7]:
b.reshape((4,))

array([1, 2, 3, 4])

#### If we don't know otheer dimension then pass -1 as other value. Note: we can't use -1 more than once. 

In [8]:
a.reshape((1,-1))

array([[1, 2, 3, 4]])

In [9]:
a.reshape((-1,1))

array([[1],
       [2],
       [3],
       [4]])

#### Flatting of multi dimensional array


In [10]:
b

array([[1, 2],
       [3, 4]])

In [11]:
b.reshape(-1)

array([1, 2, 3, 4])

### Creating arrays computationally 

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.arange(start=1,stop=10,step=0.1,dtype='double')
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [14]:
a=np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
a = np.zeros((2,1))
a

array([[0.],
       [0.]])

In [16]:
oneCol = np.ones((5,))  # a single vector of ones
zeroCols = np.zeros((5,2))  # two columns of zeros
np.column_stack((oneCol, zeroCols))  # 5x3 columns

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

### Function and Comparison vectors

In [18]:
a = np.arange(10).reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
a = 2**a -1 
a 

array([[  0,   1],
       [  3,   7],
       [ 15,  31],
       [ 63, 127],
       [255, 511]])

In [20]:
a = a>100
a

array([[False, False],
       [False, False],
       [False, False],
       [False,  True],
       [ True,  True]])

### Array Indexing and Slicing


In [21]:
a = np.arange(12)
a[::3]

array([0, 3, 6, 9])

In [22]:
a[2:11]= -1
a

array([ 0,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 11])

In [23]:
a[[2,3,4]] #extract multiple elements in one go

array([-1, -1, -1])

In [24]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a[1,2] #2nd row, 3rd column

6

In [26]:
a[1] #2nd row

array([4, 5, 6, 7])

In [27]:
a[:,2] #all rows 3rd column

array([ 2,  6, 10])

In [28]:
a[:2] #first 2 rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### Boolean indexing

In [29]:
a = np.array([1,2,7,8])
i = np.array([True, False, True, False])
a[i]

array([1, 7])

In [30]:
a>5

array([False, False,  True,  True])

In [31]:
a[a>5]

array([7, 8])

### Random numbers


np.random.choice(N) can be used to create random numbers from 0 to N-1.
size determines the shape of the resulting object

In [32]:
a = np.random.choice(6,size=(2,3))
a

array([[5, 5, 4],
       [5, 5, 5]])

random.normal(loc, scale, size) generates normally distributed random numbers. The distribution is centered at loc and its variance is scale

In [37]:
a = np.random.normal(100,10,size=(3,4))
a

array([[ 98.34199113, 111.87673634,  87.21591878, 116.84535312],
       [ 91.10908716, 107.67488906,  92.10028229, 110.67644748],
       [ 91.92444772, 108.94821002, 108.86275353,  96.20757082]])

random.binomial(n, p, size) creates random binomials where probability of success is p and sample size is n

In [38]:
np.random.binomial(2, 0.5, size=(2,4))

array([[0, 1, 1, 2],
       [1, 2, 2, 0]])

random.uniform(low, high, size) creates uniformly distributed random numbers in the interval [low, high]

In [39]:
np.random.uniform(-1, 1, size=(3,4))  # random numbers in [-1, 1]

array([[-0.17424878,  0.67405695,  0.13432801, -0.97568774],
       [ 0.68234768,  0.88870751,  0.53640446, -0.3414835 ],
       [ 0.35803361, -0.85102428, -0.38250072,  0.73203385]])

### Statistical functions 

In [40]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a.sum()

66

In [42]:
a.sum(axis=0) # add rows, preserve columns

array([12, 15, 18, 21])

In [43]:
a.sum(axis=1) # add columns, preserve rows

array([ 6, 22, 38])

The other statistical functions include:

mean for average 

median for median

var for variance

std for standard deviation

np.percentile and np.quantile for quantiles